version: '3'

services:
  ingest:
    container_name: ingest
    image: vivshaw/politeiamancer-ingest:${VERSION}
    depends_on:
      - kafka1
      - cassandra
    environment:
        - VERSION=${VERSION}
    env_file:
      - ./ingest/praw_creds.env

  analyze:
    container_name: analyze
    image: vivshaw/politeiamancer-analyze:${VERSION}
    depends_on:
      - kafka1
      - cassandra

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888

  # can't be named `kafka` or else you will get this fun bug:
  # https://github.com/confluentinc/schema-registry/issues/689
  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    hostname: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  cassandra:
      container_name: cassandra
      image: cassandra:4.1.4
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"

  cassandra-init:
      container_name: cassandra-init
      image: cassandra:4.1.4
      depends_on:
        - cassandra
      volumes:
        - ./cassandra/schema.cql:/schema.cql
      command: /bin/bash -c "sleep 60 && echo loading Cassandra keyspace... && cqlsh cassandra -f /schema.cql"